### ISSUE TITLE
Are you sure that the IGPU acceleration of amd is working properly?

### ISSUE THREAD

**Issue by Kanepan** [JamisonMurphy/Legion-5-Pro-Hackintosh#10]
Are you sure that the IGPU acceleration of amd is working properly?
thanks!

**Comment by JamisonMurphy** [comment]
yes, use this kext https://github.com/NootInc/NootedRed

**Comment by Kanepan** [comment]
可以中文交流吗？
但是 chrome 硬件加速不行， 还有永 parsec硬件解码也不行

**Comment by JamisonMurphy** [comment]
NootedRed项目显示硬解、软解都还没开发完，所以此结果在预期中

**Comment by Kanepan** [comment]
> NootedRed项目显示硬解、软解都还没开发完，所以此结果在预期中

感谢
