### ISSUE TITLE
SAME LAPTOP USB ISSUE

### ISSUE THREAD

**Issue by Rxxbertx** [JamisonMurphy/Legion-5-Pro-Hackintosh#11]
After the installation I try to activate GUX and XHCI1 and I can't boot, it gets stuck on random sites

**Comment by Rxxbertx** [comment]
Do you have USBRELEASEOWNERSHIP active?

**Comment by JamisonMurphy** [comment]
make sure install this kext https://github.com/RattletraPM/GUX-RyzenXHCIFix

**Comment by Rxxbertx** [comment]
The real fix is using TSCTIMEOUT quirk (like your EFI)
