### ISSUE TITLE
关于ALC287

### ISSUE THREAD

**Issue by isKoi** [JamisonMurphy/Legion-5-Pro-Hackintosh#13]
对Legion 5 Pro（R9000p）机型定制了[AppleALC驱动](https://github.com/isKoi/AppleALC/actions/runs/6450306744)，这个版本剔除了其他声卡只保留ALC287，layout-id为21，在我的设备下正常运行。我对layout-id不太了解，编译了[另外一个版本](https://github.com/isKoi/AppleALC/actions/runs/6450587256)，在保留其他声卡驱动基础上加入了R9000p的定制ALC287，layout-id为13，此版本麦克风无法工作，后面排查发现是layout-id的问题，目前已知layout-id为21可正常工作，但这个layout-id被[commit](https://github.com/acidanthera/AppleALC/pull/794)占用了

**Comment by JamisonMurphy** [comment]
AppleALC v1.8.8应该修复了：https://github.com/acidanthera/AppleALC/releases/tag/1.8.8
