### ISSUE TITLE
external display support

### ISSUE THREAD

**Issue by RoboCrafty** [JamisonMurphy/Legion-5-Pro-Hackintosh#14]
Not exactly an issue (not sure) but could you mention if we can use external monitors with macOS on this? I’m not sure if any of the type C ports is connected to the iGPU but I think one of them is. Please confirm

**Comment by JamisonMurphy** [comment]
unsupported, no DP lane connected to type-c.
![image](https://github.com/JamisonMurphy/Legion-5-Pro-Hackintosh/assets/115403380/38a6729c-53f2-49a6-9389-7d588346388c)
Intel laptop for example :
![image](https://github.com/JamisonMurphy/Legion-5-Pro-Hackintosh/assets/115403380/2b2b2c52-e3e6-4870-b348-df138c11a325)
