### ISSUE TITLE
TrackPad does not work

### ISSUE THREAD

**Issue by junzhin** [JamisonMurphy/Legion-5-Pro-Hackintosh#4]
Hi, I tried to use your efi on myR9000p 3060, it works very well except for the trackpad which I am unable to  use, do you have any idea why it does not work

Thank you!

**Comment by JamisonMurphy** [comment]
I haven't looked into the touchpad yet, thought the first priority was to solve the usb problem

**Comment by junzhin** [comment]
Yes, you are right, I found another efi on GitHub in this [link](https://github.com/kalkmann/Legion-5600H-Hackintosh), and it claims that the touchpad works in that case.  You might want to take a look, the solution does not work for me.

**Comment by JamisonMurphy** [comment]
Solved
