### ISSUE TITLE
Bluetoooth not working

### ISSUE THREAD

**Issue by JSPRKWAN** [JamisonMurphy/Legion-5-Pro-Hackintosh#5]
AX210 Wi-Fi works fine, but bluetooth is not working. Already enable all the kexts.

**Comment by JamisonMurphy** [comment]
try this https://github.com/OpenIntelWireless/itlwm/issues/878#issuecomment-1575359788
and you need to enable both XHC port ,and use replug way to boot.

Close for now (If any other people have this issue reopen it)
