### ISSUE TITLE
Error on com.apple.xpc.lanuchd

### ISSUE THREAD

**Issue by isKoi** [JamisonMurphy/Legion-5-Pro-Hackintosh#7]
![D435C475-EC1A-4F44-9C9D-D5AE4E87D362](https://github.com/JamisonMurphy/Legion-5-Pro-Hackintosh/assets/83289881/ea0ced00-1979-4e6d-85e1-5bdef9198683)

**Comment by JamisonMurphy** [comment]
what's your SSD? and disable one XHC port in bios (see Readme)

**Comment by isKoi** [comment]
> what's your SSD? and disable one XHC port in bios (see Readme)

Thank you for your reply
My SSD model is `SKHynix HFS512GDE9X084N` and I disabled it with aml
now successfully installed ventura13.3
